package com.stu.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_id
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_name
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_gender
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    private String empGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_email
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.d_id
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_id
     *
     * @return the value of tbl_emp.emp_id
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_id
     *
     * @param empId the value for tbl_emp.emp_id
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_name
     *
     * @return the value of tbl_emp.emp_name
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_name
     *
     * @param empName the value for tbl_emp.emp_name
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_gender
     *
     * @return the value of tbl_emp.emp_gender
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_gender
     *
     * @param empGender the value for tbl_emp.emp_gender
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_email
     *
     * @return the value of tbl_emp.emp_email
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_email
     *
     * @param empEmail the value for tbl_emp.emp_email
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.d_id
     *
     * @return the value of tbl_emp.d_id
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.d_id
     *
     * @param dId the value for tbl_emp.d_id
     *
     * @mbg.generated Thu Jul 26 13:16:17 CST 2018
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}